# Generated by Django 3.2.14 on 2023-09-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='result_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='result_url',
            field=models.URLField(null=True),
        ),
    ]
